### ISSUE TITLE
works with openjdk

### ISSUE THREAD

**Issue by phiresky** [chenkelmann/neo2-awt-hack#1]
> If you successfully use it for OpenJDK 8, please let me know.

Can confirm this works on Arch, 64 bit, Android Studio 1.2, openjdk version "1.8.0_45", using 

```
echo -Xbootclasspath/p:/path/to/neo2-awt-hack-0.4-java8oracle.jar >> ~/.AndroidStudio1.2/studio64.vmoptions
```

**Comment by koehlma** [comment]
Me too, thank you very much for this great hack.

**Comment by Viatorus** [comment]
Thank you so much!!!!

**Comment by tkarrass** [comment]
Idea in its go flavor GoLand broke things terribly with the last major update. So I'm happy to add:

I can confirm this hack works for GoLand 2020.3 (OpenJDK 11.0.9) just fine using the --patch-module way, too.

It turns out to be a live saver for I'm able to concentrate on hacking again rather than debugging the IDE/JRE.
Love it! Thank you so much!

**Comment by chenkelmann** [comment]
Please note that with the latest IntelliJ versions, this hack is not necessary anymore: https://youtrack.jetbrains.com/issue/IDEA-197762
