### ISSUE TITLE
Build fails with Java 9

### ISSUE THREAD

**Issue by morwel** [chenkelmann/neo2-awt-hack#2]
I'm using Arch Linux and when trying to build the fix I get a compilation error.

`[ERROR] COMPILATION ERROR :` 
`[INFO] -------------------------------------------------------------`
`[ERROR] Source option 1.5 is no longer supported. Use 1.6 or later.`
`[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.`

After adding 

`  <build>`
`    <plugins>`
`        <plugin>`
`            <groupId>org.apache.maven.plugins</groupId>`
`            <artifactId>maven-compiler-plugin</artifactId>`
`            <version>3.6.1</version>`
`            <configuration>`
`                <source>1.8</source>`
`                <target>1.8</target>`
`            </configuration>`
`        </plugin>`
`    </plugins>`
`  </build>`

to pom.xml it starts building, but then fails with

`ERROR] COMPILATION ERROR : `
`[INFO] -------------------------------------------------------------`
`[ERROR] ...neo2-awt-hack-master/src/main/java/java/awt/event/KeyEvent.java:[919,48] <anonymous java.awt.event.KeyEvent$1> is not abstract and does not override abstract method isProxyActive(java.awt.event.KeyEvent) in sun.awt.AWTAccessor.KeyEventAccessor`

Unfortunately I don't know enough about java to investigate any further myself.

I'm using maven == 3.5.2 and openjdk == 9.u181.

**Comment by chenkelmann** [comment]
The error message means that code that the hack overwrites / augments is not present anymore. This is not surprising, as the hack was meant for Java 1.5. It overwrites internal classes of the JDK (which is really, really bad and should normally never be done - hence the "-hack" in the project name).
This means that the solution cannot be applied to JDK 9 anymore. It would have to be written completely from scratch - if it is even possible to modify awt events low-level in JDK 9. Are you sure you still need it? For me everything has been fine with various Linux / JDK versions for some time now, which is why I did not maintain the hack anymore - it just wasn't necessary, everything worked out-of-the-box.

Regrettably, I neither have Arch Linux to test nor the time to re-start finding a solution from scratch, so I have to close this issue as "won't fix".

**Comment by morwel** [comment]
Thanks for the quick response.
I'm using PyCharm and the Mod4 arrow keys aren't working, while other Mod4 stuff is. So maybe there's another way to get this working.
